/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NextRouteRouteImport } from './routes/next/route'
import { Route as LegacyRouteRouteImport } from './routes/_legacy/route'
import { Route as LegacyIndexRouteImport } from './routes/_legacy/index'
import { Route as NextConnectRouteImport } from './routes/next/connect'
import { Route as LegacySettingsRouteImport } from './routes/_legacy/settings'
import { Route as LegacyOldRouteImport } from './routes/_legacy/old'
import { Route as LegacyWalletWalletIdRouteImport } from './routes/_legacy/wallet.$walletId'

const NextRouteRoute = NextRouteRouteImport.update({
  id: '/next',
  path: '/next',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyRouteRoute = LegacyRouteRouteImport.update({
  id: '/_legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyIndexRoute = LegacyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegacyRouteRoute,
} as any)
const NextConnectRoute = NextConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => NextRouteRoute,
} as any)
const LegacySettingsRoute = LegacySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LegacyRouteRoute,
} as any)
const LegacyOldRoute = LegacyOldRouteImport.update({
  id: '/old',
  path: '/old',
  getParentRoute: () => LegacyRouteRoute,
} as any)
const LegacyWalletWalletIdRoute = LegacyWalletWalletIdRouteImport.update({
  id: '/wallet/$walletId',
  path: '/wallet/$walletId',
  getParentRoute: () => LegacyRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LegacyIndexRoute
  '/next': typeof NextRouteRouteWithChildren
  '/old': typeof LegacyOldRoute
  '/settings': typeof LegacySettingsRoute
  '/next/connect': typeof NextConnectRoute
  '/wallet/$walletId': typeof LegacyWalletWalletIdRoute
}
export interface FileRoutesByTo {
  '/next': typeof NextRouteRouteWithChildren
  '/old': typeof LegacyOldRoute
  '/settings': typeof LegacySettingsRoute
  '/next/connect': typeof NextConnectRoute
  '/': typeof LegacyIndexRoute
  '/wallet/$walletId': typeof LegacyWalletWalletIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_legacy': typeof LegacyRouteRouteWithChildren
  '/next': typeof NextRouteRouteWithChildren
  '/_legacy/old': typeof LegacyOldRoute
  '/_legacy/settings': typeof LegacySettingsRoute
  '/next/connect': typeof NextConnectRoute
  '/_legacy/': typeof LegacyIndexRoute
  '/_legacy/wallet/$walletId': typeof LegacyWalletWalletIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/next'
    | '/old'
    | '/settings'
    | '/next/connect'
    | '/wallet/$walletId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/next'
    | '/old'
    | '/settings'
    | '/next/connect'
    | '/'
    | '/wallet/$walletId'
  id:
    | '__root__'
    | '/_legacy'
    | '/next'
    | '/_legacy/old'
    | '/_legacy/settings'
    | '/next/connect'
    | '/_legacy/'
    | '/_legacy/wallet/$walletId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LegacyRouteRoute: typeof LegacyRouteRouteWithChildren
  NextRouteRoute: typeof NextRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/next': {
      id: '/next'
      path: '/next'
      fullPath: '/next'
      preLoaderRoute: typeof NextRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_legacy': {
      id: '/_legacy'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LegacyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_legacy/': {
      id: '/_legacy/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LegacyIndexRouteImport
      parentRoute: typeof LegacyRouteRoute
    }
    '/next/connect': {
      id: '/next/connect'
      path: '/connect'
      fullPath: '/next/connect'
      preLoaderRoute: typeof NextConnectRouteImport
      parentRoute: typeof NextRouteRoute
    }
    '/_legacy/settings': {
      id: '/_legacy/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LegacySettingsRouteImport
      parentRoute: typeof LegacyRouteRoute
    }
    '/_legacy/old': {
      id: '/_legacy/old'
      path: '/old'
      fullPath: '/old'
      preLoaderRoute: typeof LegacyOldRouteImport
      parentRoute: typeof LegacyRouteRoute
    }
    '/_legacy/wallet/$walletId': {
      id: '/_legacy/wallet/$walletId'
      path: '/wallet/$walletId'
      fullPath: '/wallet/$walletId'
      preLoaderRoute: typeof LegacyWalletWalletIdRouteImport
      parentRoute: typeof LegacyRouteRoute
    }
  }
}

interface LegacyRouteRouteChildren {
  LegacyOldRoute: typeof LegacyOldRoute
  LegacySettingsRoute: typeof LegacySettingsRoute
  LegacyIndexRoute: typeof LegacyIndexRoute
  LegacyWalletWalletIdRoute: typeof LegacyWalletWalletIdRoute
}

const LegacyRouteRouteChildren: LegacyRouteRouteChildren = {
  LegacyOldRoute: LegacyOldRoute,
  LegacySettingsRoute: LegacySettingsRoute,
  LegacyIndexRoute: LegacyIndexRoute,
  LegacyWalletWalletIdRoute: LegacyWalletWalletIdRoute,
}

const LegacyRouteRouteWithChildren = LegacyRouteRoute._addFileChildren(
  LegacyRouteRouteChildren,
)

interface NextRouteRouteChildren {
  NextConnectRoute: typeof NextConnectRoute
}

const NextRouteRouteChildren: NextRouteRouteChildren = {
  NextConnectRoute: NextConnectRoute,
}

const NextRouteRouteWithChildren = NextRouteRoute._addFileChildren(
  NextRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LegacyRouteRoute: LegacyRouteRouteWithChildren,
  NextRouteRoute: NextRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
