/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OldRouteImport } from './routes/old'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletWalletIdRouteImport } from './routes/wallet.$walletId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OldRoute = OldRouteImport.update({
  id: '/old',
  path: '/old',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletWalletIdRoute = WalletWalletIdRouteImport.update({
  id: '/wallet/$walletId',
  path: '/wallet/$walletId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/old': typeof OldRoute
  '/settings': typeof SettingsRoute
  '/wallet/$walletId': typeof WalletWalletIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/old': typeof OldRoute
  '/settings': typeof SettingsRoute
  '/wallet/$walletId': typeof WalletWalletIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/old': typeof OldRoute
  '/settings': typeof SettingsRoute
  '/wallet/$walletId': typeof WalletWalletIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/connect' | '/old' | '/settings' | '/wallet/$walletId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/connect' | '/old' | '/settings' | '/wallet/$walletId'
  id: '__root__' | '/' | '/connect' | '/old' | '/settings' | '/wallet/$walletId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  OldRoute: typeof OldRoute
  SettingsRoute: typeof SettingsRoute
  WalletWalletIdRoute: typeof WalletWalletIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/old': {
      id: '/old'
      path: '/old'
      fullPath: '/old'
      preLoaderRoute: typeof OldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/$walletId': {
      id: '/wallet/$walletId'
      path: '/wallet/$walletId'
      fullPath: '/wallet/$walletId'
      preLoaderRoute: typeof WalletWalletIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  OldRoute: OldRoute,
  SettingsRoute: SettingsRoute,
  WalletWalletIdRoute: WalletWalletIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
