/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NextRouteRouteImport } from './routes/next/route'
import { Route as LegacyRouteRouteImport } from './routes/_legacy/route'
import { Route as LegacyIndexRouteImport } from './routes/_legacy/index'
import { Route as NextDashboardRouteImport } from './routes/next/dashboard'
import { Route as NextConnectRouteImport } from './routes/next/connect'
import { Route as LegacySettingsRouteImport } from './routes/_legacy/settings'
import { Route as NextDashboardIndexRouteImport } from './routes/next/dashboard/index'
import { Route as NextDashboardOffersRouteImport } from './routes/next/dashboard/offers'
import { Route as NextDashboardFaqRouteImport } from './routes/next/dashboard/faq'
import { Route as LegacyWalletWalletIdRouteImport } from './routes/_legacy/wallet.$walletId'
import { Route as NextDashboardWalletWalletIdRouteImport } from './routes/next/dashboard/wallet.$walletId'

const NextRouteRoute = NextRouteRouteImport.update({
  id: '/next',
  path: '/next',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyRouteRoute = LegacyRouteRouteImport.update({
  id: '/_legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyIndexRoute = LegacyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegacyRouteRoute,
} as any)
const NextDashboardRoute = NextDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => NextRouteRoute,
} as any)
const NextConnectRoute = NextConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => NextRouteRoute,
} as any)
const LegacySettingsRoute = LegacySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LegacyRouteRoute,
} as any)
const NextDashboardIndexRoute = NextDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NextDashboardRoute,
} as any)
const NextDashboardOffersRoute = NextDashboardOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => NextDashboardRoute,
} as any)
const NextDashboardFaqRoute = NextDashboardFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => NextDashboardRoute,
} as any)
const LegacyWalletWalletIdRoute = LegacyWalletWalletIdRouteImport.update({
  id: '/wallet/$walletId',
  path: '/wallet/$walletId',
  getParentRoute: () => LegacyRouteRoute,
} as any)
const NextDashboardWalletWalletIdRoute =
  NextDashboardWalletWalletIdRouteImport.update({
    id: '/wallet/$walletId',
    path: '/wallet/$walletId',
    getParentRoute: () => NextDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LegacyIndexRoute
  '/next': typeof NextRouteRouteWithChildren
  '/settings': typeof LegacySettingsRoute
  '/next/connect': typeof NextConnectRoute
  '/next/dashboard': typeof NextDashboardRouteWithChildren
  '/wallet/$walletId': typeof LegacyWalletWalletIdRoute
  '/next/dashboard/faq': typeof NextDashboardFaqRoute
  '/next/dashboard/offers': typeof NextDashboardOffersRoute
  '/next/dashboard/': typeof NextDashboardIndexRoute
  '/next/dashboard/wallet/$walletId': typeof NextDashboardWalletWalletIdRoute
}
export interface FileRoutesByTo {
  '/next': typeof NextRouteRouteWithChildren
  '/settings': typeof LegacySettingsRoute
  '/next/connect': typeof NextConnectRoute
  '/': typeof LegacyIndexRoute
  '/wallet/$walletId': typeof LegacyWalletWalletIdRoute
  '/next/dashboard/faq': typeof NextDashboardFaqRoute
  '/next/dashboard/offers': typeof NextDashboardOffersRoute
  '/next/dashboard': typeof NextDashboardIndexRoute
  '/next/dashboard/wallet/$walletId': typeof NextDashboardWalletWalletIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_legacy': typeof LegacyRouteRouteWithChildren
  '/next': typeof NextRouteRouteWithChildren
  '/_legacy/settings': typeof LegacySettingsRoute
  '/next/connect': typeof NextConnectRoute
  '/next/dashboard': typeof NextDashboardRouteWithChildren
  '/_legacy/': typeof LegacyIndexRoute
  '/_legacy/wallet/$walletId': typeof LegacyWalletWalletIdRoute
  '/next/dashboard/faq': typeof NextDashboardFaqRoute
  '/next/dashboard/offers': typeof NextDashboardOffersRoute
  '/next/dashboard/': typeof NextDashboardIndexRoute
  '/next/dashboard/wallet/$walletId': typeof NextDashboardWalletWalletIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/next'
    | '/settings'
    | '/next/connect'
    | '/next/dashboard'
    | '/wallet/$walletId'
    | '/next/dashboard/faq'
    | '/next/dashboard/offers'
    | '/next/dashboard/'
    | '/next/dashboard/wallet/$walletId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/next'
    | '/settings'
    | '/next/connect'
    | '/'
    | '/wallet/$walletId'
    | '/next/dashboard/faq'
    | '/next/dashboard/offers'
    | '/next/dashboard'
    | '/next/dashboard/wallet/$walletId'
  id:
    | '__root__'
    | '/_legacy'
    | '/next'
    | '/_legacy/settings'
    | '/next/connect'
    | '/next/dashboard'
    | '/_legacy/'
    | '/_legacy/wallet/$walletId'
    | '/next/dashboard/faq'
    | '/next/dashboard/offers'
    | '/next/dashboard/'
    | '/next/dashboard/wallet/$walletId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LegacyRouteRoute: typeof LegacyRouteRouteWithChildren
  NextRouteRoute: typeof NextRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/next': {
      id: '/next'
      path: '/next'
      fullPath: '/next'
      preLoaderRoute: typeof NextRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_legacy': {
      id: '/_legacy'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LegacyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_legacy/': {
      id: '/_legacy/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LegacyIndexRouteImport
      parentRoute: typeof LegacyRouteRoute
    }
    '/next/dashboard': {
      id: '/next/dashboard'
      path: '/dashboard'
      fullPath: '/next/dashboard'
      preLoaderRoute: typeof NextDashboardRouteImport
      parentRoute: typeof NextRouteRoute
    }
    '/next/connect': {
      id: '/next/connect'
      path: '/connect'
      fullPath: '/next/connect'
      preLoaderRoute: typeof NextConnectRouteImport
      parentRoute: typeof NextRouteRoute
    }
    '/_legacy/settings': {
      id: '/_legacy/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LegacySettingsRouteImport
      parentRoute: typeof LegacyRouteRoute
    }
    '/next/dashboard/': {
      id: '/next/dashboard/'
      path: '/'
      fullPath: '/next/dashboard/'
      preLoaderRoute: typeof NextDashboardIndexRouteImport
      parentRoute: typeof NextDashboardRoute
    }
    '/next/dashboard/offers': {
      id: '/next/dashboard/offers'
      path: '/offers'
      fullPath: '/next/dashboard/offers'
      preLoaderRoute: typeof NextDashboardOffersRouteImport
      parentRoute: typeof NextDashboardRoute
    }
    '/next/dashboard/faq': {
      id: '/next/dashboard/faq'
      path: '/faq'
      fullPath: '/next/dashboard/faq'
      preLoaderRoute: typeof NextDashboardFaqRouteImport
      parentRoute: typeof NextDashboardRoute
    }
    '/_legacy/wallet/$walletId': {
      id: '/_legacy/wallet/$walletId'
      path: '/wallet/$walletId'
      fullPath: '/wallet/$walletId'
      preLoaderRoute: typeof LegacyWalletWalletIdRouteImport
      parentRoute: typeof LegacyRouteRoute
    }
    '/next/dashboard/wallet/$walletId': {
      id: '/next/dashboard/wallet/$walletId'
      path: '/wallet/$walletId'
      fullPath: '/next/dashboard/wallet/$walletId'
      preLoaderRoute: typeof NextDashboardWalletWalletIdRouteImport
      parentRoute: typeof NextDashboardRoute
    }
  }
}

interface LegacyRouteRouteChildren {
  LegacySettingsRoute: typeof LegacySettingsRoute
  LegacyIndexRoute: typeof LegacyIndexRoute
  LegacyWalletWalletIdRoute: typeof LegacyWalletWalletIdRoute
}

const LegacyRouteRouteChildren: LegacyRouteRouteChildren = {
  LegacySettingsRoute: LegacySettingsRoute,
  LegacyIndexRoute: LegacyIndexRoute,
  LegacyWalletWalletIdRoute: LegacyWalletWalletIdRoute,
}

const LegacyRouteRouteWithChildren = LegacyRouteRoute._addFileChildren(
  LegacyRouteRouteChildren,
)

interface NextDashboardRouteChildren {
  NextDashboardFaqRoute: typeof NextDashboardFaqRoute
  NextDashboardOffersRoute: typeof NextDashboardOffersRoute
  NextDashboardIndexRoute: typeof NextDashboardIndexRoute
  NextDashboardWalletWalletIdRoute: typeof NextDashboardWalletWalletIdRoute
}

const NextDashboardRouteChildren: NextDashboardRouteChildren = {
  NextDashboardFaqRoute: NextDashboardFaqRoute,
  NextDashboardOffersRoute: NextDashboardOffersRoute,
  NextDashboardIndexRoute: NextDashboardIndexRoute,
  NextDashboardWalletWalletIdRoute: NextDashboardWalletWalletIdRoute,
}

const NextDashboardRouteWithChildren = NextDashboardRoute._addFileChildren(
  NextDashboardRouteChildren,
)

interface NextRouteRouteChildren {
  NextConnectRoute: typeof NextConnectRoute
  NextDashboardRoute: typeof NextDashboardRouteWithChildren
}

const NextRouteRouteChildren: NextRouteRouteChildren = {
  NextConnectRoute: NextConnectRoute,
  NextDashboardRoute: NextDashboardRouteWithChildren,
}

const NextRouteRouteWithChildren = NextRouteRoute._addFileChildren(
  NextRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LegacyRouteRoute: LegacyRouteRouteWithChildren,
  NextRouteRoute: NextRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
